export const expenseStyles = {
  container: {
    height: "100vh",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#f5f5f5",
  },
  card: {
    width: "300px",
    background: "#fff",
    padding: "15px",
    borderRadius: "10px",
    boxShadow: "0 4px 10px rgba(0,0,0,0.1)",
  },
  cardContainer: {
  display: "flex",
  gap: "20px",
},
  title: {
    marginBottom: "20px",
  },
  input: {
    width: "92%",
    padding: "10px",
    marginBottom: "12px",
    borderRadius: "6px",
    border: "1px solid #ccc",
  },
  button: {
    width: "100%",
    padding: "12px",
    marginBottom: "10px",
    backgroundColor: "#4CAF50",
    color: "#fff",
    border: "none",
    borderRadius: "100px",
    cursor: "pointer",
    fontSize: "16px",
  },
  buttonContainer: {
    display: "flex",
    gap: "10px",
    justifyContent: "center", // aligns buttons to the left
    marginBottom: "20px",
  },
  emailButton: {
    padding: "12px 24px",
    backgroundColor: "#2196f3",
    color: "white",
    border: "none",
    borderRadius: "15px",
    cursor: "pointer",
    fontSize: "16px",
  },
  mobileButton: {
    padding: "12px 24px",
    backgroundColor: "#1976d2",
    color: "white",
    border: "none",
    borderRadius: "15px",
    cursor: "pointer",
    fontSize: "16px",
  },
  resendButtonContainer: {
    display: "flex",
    gap: "10px",
    justifyContent: "flex-end", // aligns buttons to the left
    marginBottom: "20px",
  },
  resendButton: {
    width: "100%",
    padding: "12px",
    marginBottom: "10px",
    backgroundColor: "#2196F3",
    color: "#fff",
    border: "none",
    borderRadius: "100px",
    cursor: "pointer",
    fontSize: "16px",
  },
   primaryBtn: {
    width: "100%",
    padding: "12px",
    marginBottom: "10px",
    backgroundColor: "#4CAF50",
    color: "#fff",
    border: "none",
    borderRadius: "100px",
    cursor: "pointer",
    fontSize: "16px",
  },
  secondaryBtn: {
    width: "100%",
    padding: "12px",
    marginBottom: "10px",
    backgroundColor: "#2196F3",
    color: "#fff",
    border: "none",
    borderRadius: "100px",
    cursor: "pointer",
    fontSize: "16px",
  },
  link: { color: 'blue', textDecoration: 'underline', cursor: 'pointer' }
};