export const expenseStyles = {
  container: {
    minHeight: "100vh",
    width: "100%",
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
    backgroundColor: "#e5d091",
    padding: "20px",
    boxSizing: "border-box" as const,
  },
  cardContainer: {
    display: "flex",
    flexWrap: "wrap" as const,
    gap: "16px",
    justifyContent: "center",
    width: "100%",
    maxWidth: "1100px",
  },
  card: {
    flex: "1 1 250px",
    maxWidth: "350px",
    padding: "20px",
    borderRadius: "8px",
    backgroundColor: "#fff",
    boxShadow: "0 2px 8px rgba(0,0,0,0.1)",
    textAlign: "center" as const,
  },
  title: {
    alignSelf: "center",
    marginBottom: "20px",
  },
  input: {
    width: "92%",
    padding: "10px",
    marginBottom: "12px",
    borderRadius: "6px",
    border: "1px solid #ccc",
  },
  button: {
    width: "100%",
    padding: "12px",
    marginBottom: "10px",
    backgroundColor: "#4CAF50",
    color: "#fff",
    border: "none",
    borderRadius: "100px",
    cursor: "pointer",
    fontSize: "16px",
  },
  buttonContainer: {
    display: "flex",
    gap: "10px",
    justifyContent: "center" as const,
    marginBottom: "20px",
  },
  emailButton: {
    padding: "12px 24px",
    backgroundColor: "#2196f3",
    color: "white",
    border: "none",
    borderRadius: "15px",
    cursor: "pointer",
    fontSize: "16px",
  },
  mobileButton: {
    padding: "12px 24px",
    backgroundColor: "#1976d2",
    color: "white",
    border: "none",
    borderRadius: "15px",
    cursor: "pointer",
    fontSize: "16px",
  },
  resendButtonContainer: {
    display: "flex",
    gap: "10px",
    justifyContent: "flex-end" as const,
    marginBottom: "20px",
  },
  resendButton: {
    width: "100%",
    padding: "12px",
    marginBottom: "10px",
    backgroundColor: "#2196F3",
    color: "#fff",
    border: "none",
    borderRadius: "100px",
    cursor: "pointer",
    fontSize: "16px",
  },
  primaryBtn: {
    width: "100%",
    padding: "12px",
    marginBottom: "10px",
    backgroundColor: "#4CAF50",
    color: "#fff",
    border: "none",
    borderRadius: "100px",
    cursor: "pointer",
    fontSize: "16px",
  },
  secondaryBtn: {
    width: "100%",
    padding: "12px",
    marginBottom: "10px",
    backgroundColor: "#2196F3",
    color: "#fff",
    border: "none",
    borderRadius: "100px",
    cursor: "pointer",
    fontSize: "16px",
  },
  link: {
    color: "blue",
    textDecoration: "underline",
    cursor: "pointer",
  },

  // Bottom Nav
  bottomNav: {
    position: "fixed" as const,
    bottom: 0,
    left: 0,
    right: 0,
    display: "flex",
    justifyContent: "space-around" as const,
    backgroundColor: "#fff",
    borderTop: "1px solid #ddd",
    padding: "10px 0 16px",
    zIndex: 100,
  },
  navItem: {
    display: "flex" as const,
    flexDirection: "column" as const,
    alignItems: "center" as const,
    gap: "4px",
    background: "transparent",
    border: "none",
    cursor: "pointer",
    padding: "4px 16px",
    fontFamily: "inherit",
  },
  navIcon: {
    width: "24px",
    height: "24px",
  },
  navLabel: {
    fontSize: "11px",
  },

  // Recent Expenses
  recentSection: {
    width: "100%",
    maxWidth: "700px",
    marginTop: "20px",
    paddingBottom: "80px",
  },
  recentHeader: {
    display: "flex" as const,
    justifyContent: "space-between" as const,
    alignItems: "center" as const,
    marginBottom: "12px",
  },
  recentTitle: {
    fontSize: "16px",
    fontWeight: "500" as const,
    color: "#2C2C2A",
  },
  addExpenseBtn: {
    background: "#534AB7",
    color: "#fff",
    border: "none",
    borderRadius: "8px",
    padding: "8px 16px",
    cursor: "pointer",
    fontSize: "13px",
    fontWeight: "500" as const,
    display: "flex" as const,
    alignItems: "center" as const,
    gap: "6px",
  },
  expenseItem: {
    display: "flex" as const,
    alignItems: "center" as const,
    gap: "12px",
    backgroundColor: "#fff",
    borderRadius: "12px",
    border: "0.5px solid #ddd",
    padding: "12px 16px",
    marginBottom: "8px",
  },
  expenseIconCircle: {
    width: "36px",
    height: "36px",
    borderRadius: "50%",
    overflow: "hidden" as const,
    flexShrink: 0,
    display: "flex" as const,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    backgroundColor: "#f0f0f0",
  },
  expenseIconImg: {
    width: "20px",
    height: "20px",
  },
  expenseInfo: {
    flex: 1,
  },
  expenseName: {
    fontSize: "14px",
    fontWeight: "500" as const,
    color: "#2C2C2A",
  },
  expenseDate: {
    fontSize: "12px",
    color: "#888",
    marginTop: "2px",
  },
  expenseAmount: {
    fontSize: "15px",
    fontWeight: "500" as const,
    color: "#A32D2D",
  },
};